project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Étienne Sinotte"
  search: false
  page-footer:
    left: "Made with [Quarto](https://quarto.org/)"
  navbar:
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - dissemination.qmd


format:
  html:
    theme: minty
    toc: false
    page-layout: full

editor: visual