project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Étienne Sinotte"
  favicon: "assets/favicon.png"
  search: false
  navbar:
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - text: "FR/ES"
        menu:
          - href: index-fr.qmd
            text: "(FR) À propos"
          - href: index-es.qmd
            text: "(ES) Sobre mí"


format:
  html:
    theme: 
      - default
      - custom.scss
    toc: false
    page-layout: full

editor: visual