---
title: "Research"
body-class: "page-research"
---

## Projects

#### Uprooted Democracy: Displacement and the Politics of Recognition (Research Project)

*Examines why states recognize some forms of displacement (climate-, development-, and persecution-led) while rendering others legally invisible, and what this reveals about democratic quality in Latin America.*

## Articles

#### Sustaining Coproduction Despite Intermittent State Disengagement: Peru's Indigenous COVID Commands, in *Latin American Politics and Society*, in press.

*During the COVID-19 pandemic, Peru established Indigenous COVID Commands (ICCs) to coordinate emergency responses in Amazonian communities. Scholars have emphasized these spaces’ limited effectiveness and shallow collaborative processes. Yet ICCs functioned unevenly: this article examines the La Convención ICC (Cusco), which, while facing common pitfalls, proved more effective than others due to a legacy of health-related collaboration and the active involvement of NGOs. Where the state’s engagement in the collaborative process was intermittent, resource-rich, embedded NGOs sustained the infrastructure of coproduction, negotiating with indigenous leaders and disseminating interculturally appropriate information to convince communities distrustful of the state to accept vaccination. The case specifies the conditions under which civil society can carry coproduction through such episodes, producing a hybrid of community-led and symbolic coproduction. The article contributes to scholarship on crisis governance and state capacity by showing how localized networks and non-state actors can bolster policy implementation in medium-capacity states.*

## Chapters

#### [Definitions of northern/rural/remote/peripheric communities in Canada](https://doi.org/10.4337/9781035338931.00012), in the *Research Companion to the Periphery and Peripheral Regions: Concepts, Diagnosis, Dilemmas, edited by Jerzy Banski*, 2025.

(with François Brouard, Natalya Brown, and Manuel Litalien)

*Inconsistent definitions for northern, rural, and remote Canadian communities lead to oversimplified classifications that ignore regional diversity and result in poorly tailored public policies and a philanthropic sector which neglects smaller communities in favor of urban centers. A nuanced, multi-factor approach is essential to accurately identify community needs and ensure the equitable delivery of social programs.*

## Book Reviews

#### [*Climate Displacement* by Jamie Draper](https://doi.org/10.1093/jrs/feaf008), in the *Journal of Refugee Studies*, 2025.

#### [*Recognition Politics: Indigenous Rights and Ethnic Conflict in the Andes* by Lorenza Fontana](https://doi.org/10.1080/08263663.2023.2281102), in the *Canadian Journal of Latin American and Caribbean Studies*, 2024.

#### [*Voice and Inequality: Poverty and Political Participation in Latin American Democracies* by Carew Boulding and Claudio Holzner](https://doi.org/10.7202/1106146ar), in *Politique et Sociétés*, 2023.

## Media

#### [Ousting of Peru’s president points to a deeper crisis](https://doi.org/10.64628/AAM.jxeyj7ppm), in *The Conversation Canada*, March 5, 2026.

## Selected Grants and Fellowships

-   Doctoral Research Fellowship from the Interuniversity Research Team on Governance and Inclusion in Latin America (ÉRIGAL) (2025-2026)

-   Canada Graduate Scholarship (Ph.D.; CGS-D) from the Social Sciences and Humanities Research Council of Canada (SSHRC) (2024-2027)

-   Canada Graduate Scholarship (M.A.; CGS-M) from the Social Sciences and Humanities Research Council of Canada (SSHRC) (2022-2023)

-   Discovery Scholarship from the University of Montreal’s School of Graduate and Postdoctoral Studies

## Affiliations

-   [Member](https://csdc-cecd.ca/etudiants/?id=697), Centre for the Study of Democratic Citizenship (CSDC) (2025-present)

-   [Member](https://www.mcgillrefugeeresearchgroup.com/members), McGill Refugee Research Group (MRRG)  (2025-present)

-   [Member](https://www.erigal.org/en_CA/le-profil/etienne-sinotte), Interuniversity Research Team on Governance and Inclusion in Latin America (ÉRIGAL) (2021-present)

-   Visiting Scholar, *Centro de Investigaciones Sociológicas, Económicas, Políticas y Antropológicas* at the *Pontificia Universidad Católica del Perú* (PUCP-CISEPA) (2025)

-   [Member](https://chaireparticipation2.odoo.com/etienne-sinotte), Chaire de recherche du Canada Participation et citoyenneté(s) (2021-2023)
